name = "Lean Project"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["«Lean Project»"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.19.0-rc3"

[[lean_lib]]
name = "«Lean Project»"
